//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PacMan.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PacMan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ABOUT {
            get {
                object obj = ResourceManager.GetObject("ABOUT", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BG_HS {
            get {
                object obj = ResourceManager.GetObject("BG_HS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BG_MAIN {
            get {
                object obj = ResourceManager.GetObject("BG_MAIN", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap entities {
            get {
                object obj = ResourceManager.GetObject("entities", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Player 0 0 32 32
        ///Blinky 32 0 32 32
        ///Clyde 64 0 32 32
        ///Inky 96 0 32 32
        ///Pinky 64 32 32 32
        ///Cherry 0 32 32 32.
        /// </summary>
        internal static string entities1 {
            get {
                return ResourceManager.GetString("entities1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GameOver {
            get {
                object obj = ResourceManager.GetObject("GameOver", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MAIN_TEXTURE {
            get {
                object obj = ResourceManager.GetObject("MAIN_TEXTURE", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TILE UL 0 0
        ///TILE RL 0 1
        ///TILE RL 0 2
        ///TILE RL 0 3
        ///TILE RL 0 4
        ///TILE RL 0 5
        ///TILE RL 0 6
        ///TILE RL 0 7
        ///TILE RL 0 8
        ///TILE RL 0 9
        ///TILE L 0 10
        ///TILE RL 0 11
        ///TILE RL 0 12
        ///TILE L 0 13
        ///TILE RL 0 14
        ///TILE RL 0 15
        ///TILE L 0 16
        ///TILE L 0 17
        ///TILE RL 0 18
        ///TILE RL 0 19
        ///TILE L 0 20
        ///TILE L 0 21
        ///TILE RL 0 22
        ///TILE RL 0 23
        ///TILE RL 0 24
        ///TILE RL 0 25
        ///TILE RL 0 26
        ///TILE L 0 27
        ///TILE RL 0 28
        ///TILE RL 0 29
        ///TILE RL 0 30
        ///TILE RL 0 31
        ///TILE RL 0 32
        ///TILE RL 0 33
        ///TILE RL 0 34
        ///TILE RL 0 35
        ///TILE RL 0 36
        ///TILE RL 0 3 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string map {
            get {
                return ResourceManager.GetString("map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] overFont {
            get {
                object obj = ResourceManager.GetObject("overFont", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full 0 0
        ///URL 1 0
        ///RDL 2 0
        ///UDL 3 0
        ///URD 0 1
        ///UL 1 1
        ///UR 2 1
        ///DL 3 1
        ///RD 0 2
        ///U 1 2
        ///L 2 2
        ///D 3 2
        ///R 0 3
        ///UD 1 3
        ///RL 2 3
        ///None 3 3
        ///STAR 0 4.
        /// </summary>
        internal static string tiles {
            get {
                return ResourceManager.GetString("tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tileTexture {
            get {
                object obj = ResourceManager.GetObject("tileTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
